CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE bank_accounts (
    iban character varying(34) NOT NULL,
    balance numeric NOT NULL,
    account_type integer NOT NULL,
    is_deleted boolean NOT NULL,
    accept_bizum boolean NOT NULL,
    CONSTRAINT "PK_bank_accounts" PRIMARY KEY (iban)
);

CREATE TABLE users (
    id uuid NOT NULL,
    name character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    username character varying(100) NOT NULL,
    dni character varying(9) NOT NULL,
    gender integer NOT NULL,
    password character varying(100) NOT NULL,
    avatar character varying(100) NOT NULL,
    phone character varying(9) NOT NULL,
    role integer NOT NULL,
    is_deleted boolean NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    CONSTRAINT "PK_users" PRIMARY KEY (id)
);

CREATE TABLE transactions (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    concept character varying(255) NOT NULL,
    amount numeric NOT NULL,
    iban_account_origin character varying(34),
    iban_account_destination character varying(34) NOT NULL,
    date timestamp with time zone NOT NULL,
    CONSTRAINT "PK_transactions" PRIMARY KEY (id),
    CONSTRAINT "FK_transactions_bank_accounts_iban_account_destination" FOREIGN KEY (iban_account_destination) REFERENCES bank_accounts (iban) ON DELETE CASCADE,
    CONSTRAINT "FK_transactions_bank_accounts_iban_account_origin" FOREIGN KEY (iban_account_origin) REFERENCES bank_accounts (iban)
);

CREATE TABLE cards (
    card_number character varying(16) NOT NULL,
    pin text NOT NULL,
    card_type integer NOT NULL,
    expiration_date timestamp with time zone NOT NULL,
    cvv text NOT NULL,
    is_deleted boolean NOT NULL,
    is_blocked boolean NOT NULL,
    user_id uuid NOT NULL,
    bank_account_iban character varying(24) NOT NULL,
    CONSTRAINT "PK_cards" PRIMARY KEY (card_number),
    CONSTRAINT "FK_cards_bank_accounts_bank_account_iban" FOREIGN KEY (bank_account_iban) REFERENCES bank_accounts (iban) ON DELETE CASCADE,
    CONSTRAINT "FK_cards_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE "UserBankAccount" (
    "UsersId" uuid NOT NULL,
    "BankAccountsId" character varying(34) NOT NULL,
    CONSTRAINT "PK_UserBankAccount" PRIMARY KEY ("UsersId", "BankAccountsId"),
    CONSTRAINT "FK_UserBankAccount_bank_accounts_BankAccountsId" FOREIGN KEY ("BankAccountsId") REFERENCES bank_accounts (iban) ON DELETE CASCADE,
    CONSTRAINT "FK_UserBankAccount_users_UsersId" FOREIGN KEY ("UsersId") REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX "IX_cards_bank_account_iban" ON cards (bank_account_iban);

CREATE INDEX "IX_cards_user_id" ON cards (user_id);

CREATE INDEX "IX_transactions_iban_account_destination" ON transactions (iban_account_destination);

CREATE INDEX "IX_transactions_iban_account_origin" ON transactions (iban_account_origin);

CREATE INDEX "IX_UserBankAccount_BankAccountsId" ON "UserBankAccount" ("BankAccountsId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240608121852_Initial', '8.0.2');

COMMIT;

