services:
  postgres-db:
    container_name: db-postgree
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    networks:
      - bankisy-network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  
  bankisy-controller:
    ports:
      - 5196:5196
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
    container_name: bankisy-controller
    restart: always
    depends_on:
      - postgres-db
    networks:
        - bankisy-network
    
networks:
  bankisy-network:
    driver: bridge    
  
volumes:
  postgres-data:
  

  