create table if not exists "__EFMigrationsHistory"
(
    "MigrationId" varchar(150) not null,
    "ProductVersion" varchar(32) not null,
    constraint "PK___EFMigrationsHistory"
    primary key ("MigrationId")
    );

create table if not exists bank_accounts
(
    iban varchar(34) not null,
    balance numeric not null,
    account_type integer not null,
    is_deleted boolean not null,
    accept_bizum boolean not null,
    constraint "PK_bank_accounts"
    primary key (iban)
    );

create table if not exists users
(
    id uuid not null,
    name varchar(100) not null,
    email varchar(100) not null,
    username varchar(100) not null,
    dni varchar(9) not null,
    gender integer not null,
    password varchar(100) not null,
    avatar varchar(100) not null,
    phone varchar(9) not null,
    role integer not null,
    is_deleted boolean not null,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
                             constraint "PK_users"
                             primary key (id)
    );

create table if not exists transactions
(
    id integer generated by default as identity,
    concept varchar(255) not null,
    amount numeric not null,
    iban_account_origin varchar(34),
    iban_account_destination varchar(34) not null,
    date timestamp with time zone not null,
                       constraint "PK_transactions"
                       primary key (id),
    constraint "FK_transactions_bank_accounts_iban_account_destination"
    foreign key (iban_account_destination) references bank_accounts
                   on delete cascade,
    constraint "FK_transactions_bank_accounts_iban_account_origin"
    foreign key (iban_account_origin) references bank_accounts
    );

create index if not exists "IX_transactions_iban_account_destination"
    on transactions (iban_account_destination);

create index if not exists "IX_transactions_iban_account_origin"
    on transactions (iban_account_origin);

create table if not exists cards
(
    card_number varchar(16) not null,
    pin text not null,
    card_type integer not null,
    expiration_date timestamp with time zone not null,
                                  cvv text not null,
                                  is_deleted boolean not null,
                                  is_blocked boolean not null,
                                  user_id uuid not null,
                                  bank_account_iban varchar(24) not null,
    constraint "PK_cards"
    primary key (card_number),
    constraint "FK_cards_bank_accounts_bank_account_iban"
    foreign key (bank_account_iban) references bank_accounts
                              on delete cascade,
    constraint "FK_cards_users_user_id"
    foreign key (user_id) references users
                              on delete cascade
    );

create index if not exists "IX_cards_bank_account_iban"
    on cards (bank_account_iban);

create index if not exists "IX_cards_user_id"
    on cards (user_id);

create table if not exists "UserBankAccount"
(
    "UsersId" uuid not null,
    "BankAccountsId" varchar(34) not null,
    constraint "PK_UserBankAccount"
    primary key ("UsersId", "BankAccountsId"),
    constraint "FK_UserBankAccount_bank_accounts_BankAccountsId"
    foreign key ("BankAccountsId") references bank_accounts
    on delete cascade,
    constraint "FK_UserBankAccount_users_UsersId"
    foreign key ("UsersId") references users
    on delete cascade
    );

create index if not exists "IX_UserBankAccount_BankAccountsId"
    on "UserBankAccount" ("BankAccountsId");


